### ISSUE TITLE
binding enums

### ISSUE THREAD

**Issue by bigworld12** [Alex141/CalcBinding#21]
hi , i really like the idea of your project , very helpful and time saver
i would like to add the feature of binding to enum values
like an enum with  
element1,
element2,
element3 

to bind like this
c:Binding path = property Is element1
please tell me if it's possible

**Comment by Alex141** [comment]
Thank you, the pleasure is mine!

Regarding for issue:
Unfortunately calcBinding doesn't support custom enums (as well as other custom classes) yet. I understand important of such support, because several issues are just about it. I'm going to implement this feauture as soon as possible (maybe even tomorrow)

**Comment by bigworld12** [comment]
Thanks for your efforts :D

**Comment by arteny** [comment]
Is there any progress with this?

**Comment by bigworld12** [comment]
i ended up using a convertor and binding to integer values

**Comment by Alex141** [comment]
[Enums](https://github.com/Alex141/CalcBinding#4-enums) are supported in version 2.3.0.0, thank you guys for your patience :))
