### ISSUE TITLE
Support for nullable types

### ISSUE THREAD

**Issue by xmedeko** [Alex141/CalcBinding#22]
I have a `bool?` property and bind it to `Visibility`:

```
Visibility="{cb:Binding 'IsConnected == null || IsConnected == false'}"
```

I got error `Binding error: one of source fields is Unset, return null`. Is it possible to work with nullable types?

**Comment by Alex141** [comment]
Thank you for issue! Yes, calcbinding works with nullable types from last (2.2.4.0) version, but there are some restrictions for two way and onewaytosourse modes. In example multibinding is used, so mode = oneway. 

Please check you have referenced latest version of library. 
The error "unset" usually appears when source property doesn't exist, so please review, whether the property is written right in path.

If you already have latest version and path is correct, let me know, I will try to resolve this situation

**Comment by xmedeko** [comment]
Yep, I have 2.2.4.0, version. Adding `Mode=OneWay` have not helped. The property exists because when I use only `Visibility="{cb:Binding 'IsConnected == null}"` then it works but it isn't wnat I need.

**Comment by Alex141** [comment]
Ok, I found one bug - keywords true and false are not supported. It is surprising that nobody did not notice it for half a year!)

But your problem is not only this. There are problems with determine type of Nullable value if it = null.
If CalcBinding meets such value, it suggests that value have type Object, because there isn't way to determine type of null value. That suggestion allows to compile Path with null values with unknown type. Next, if property change value from null to not null, CalcBinding detect that change and recompile Path with correct property type.

When property have null value, we are only allowed to write 'property == null' or 'property != null'.

So now there is not way to overcome this. 

I have an idea to add NullToVisibility flag, the same as FalseToVisibility, it can resolve exactly your problem.

**Comment by bigworld12** [comment]
In the nullable structure there is a property called hasvalue i dunnow if
you can bind to it or not but you can start from there

**Comment by xmedeko** [comment]
What about to allow some kind of type hint, e.g. like casting `(bool?)property == false`?

**Comment by bigworld12** [comment]
i think there is a good way of fixing this
1 - remove the IsConnected == null check
2 - add TargetNullValue flag in binding expression referring to the value when IsConnected is null
3 - do a check using a simple null check in the expression code and if it returns true , then apply the TargetNullValue as a result

**Comment by JGKle** [comment]
I wasn't able to get this working either - no matter what condition I put, it's always spitting out binding errors. Was this issue closed w/o a solution?
