### ISSUE TITLE
Support for Canvas.Left, etc (attached properties)

### ISSUE THREAD

**Issue by Mnuzz** [Alex141/CalcBinding#33]
A very important use case is to calculate based on the position of a component in a canvas. I don't see any support for this.  Do you know the status of this?

I need to use (Canvas.Left) + Width + (some constant integer) and (Canvas.Top) + Height  + (some constant integer) in my calculation.

**Comment by mnuzzolilo** [comment]
GetPathes is stripping out the surrounding ( and )  in (Canvas.Left). I suspect this is part of the problem.

**Comment by Alex141** [comment]
Thanks for pull request, not trivial changes, I review it and ask you questions if they appear.

**Comment by Alex141** [comment]
A dangerous change, because it can lead to a violation of parentheses behavior. Is all versions '(A.B)' was equal to 'A.B'. Althouth it is strange to put in parentheses only one property, I think we can violate some projects in runtime by that change. 
It was necessary to forbid to take properties in parentheses in first version of library.

**Comment by Mnuzz** [comment]
Yeah given the amount of time between the PR and when it was reviewed there wasn't any chance I was going to touch it again
