### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by maurosampietro** [Alex141/CalcBinding#51]
I really appreciate the effort you put in CalcBinding and i'm aware of the amount of work it is needed to keep a project going.

By the way pull requests are accumulating and new issues are not even being discussed.

If you don't have the time or inclination to support this project anymore, please consider to transfer the project to someone else.

We really need a few fixes :)

Hope to hear you
Thank you

**Comment by Alex141** [comment]
Hello, maurosampietro
Thank you for your opinion on the project. I really paused work on the project, because solving of many issues and new devemoplent requires very deep analysis of nondocumented WPF part, or is impossible because of inextensibility of the WPF architecture.

I will look at issues list again and analyse which of the problems can be solved. Also I will write review about pull requests.
