### ISSUE TITLE
porting to uwp?

### ISSUE THREAD

**Issue by jtorjo** [Alex141/CalcBinding#59]
Hi @Alex141 ,

First off, I insanely LOVE your library! I have used it for several years!
Soon (within 1 month or so), I will have to port my app to UWP. I am a beginner at UWP.

Since both WPF and UWP use binding, I would assume porting it would be easy. But since there's a request for this for 1.5 years (https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/1790), I'm asssuming it's waay more complicated than I think. 

I will have to, one way or another, port this to uwp. Any pointers as to what complications I should expect?

Background:
I **insanely hate** UWP, but for the upcoming months (until WinUI gets to version 3.0), I don't have a choice. Long story short, I want to use win2d, and using Xaml Islands is just a sad joke.

Best,
John

**Comment by Alex141** [comment]
Hi @jtorjo!

Thanks for your positive feedback :) I didn't port library because of only one reason - I didn't do it :) 
UWP isn't used at my work, so I have to study it before starting port of library. I think that it is interesting task, but I think that this task should be done by a person who will then work with it on UWP, but it is definitly not me. 

I will be very happy if you will port library :) I can answer questions if they arise

**Comment by jtorjo** [comment]
Hi @Alex141 ,

You're so lucky you don't need UWP :D 

Can't promise an exact timeframe, but 95% sure I'll do it. Will definitely keep you posted!

Best,
John
